name: mental_health_support
description: A mental health support application
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  supabase_flutter: ^1.10.25
  image_picker: ^1.0.7
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
